### ISSUE TITLE
ELIFECYCLE error when installing project dependencies on Ubuntu 20.04

### ISSUE THREAD

**Issue by nico1233** [Zamiell/hanabi-live#2207]
Hi everyone,

I tried to install hanab on my own server (Ubuntu 20.04), following [this guide](https://github.com/Zamiell/hanabi-live/blob/master/docs/INSTALL.md#installation-for-production-linux) and now faced an ELIFECYCLE error. Now I don't really know what might be wrong.

I aditionally installed npm with `sudo apt install npm` as ubuntu didn't know the npm command by default. I suppose it should have come with nvm or Node.js. You might want to add this step to the installation guide.

Anyway, this happended after running the install_dependencies.sh:

```
nico@ubuntuserver:/usr/share/nginx/hanabi-live$ sudo ./install/install_dependencies.sh
+++ dirname ./install/install_dependencies.sh
++ cd ./install
++ pwd
+ DIR=/usr/share/nginx/hanabi-live/install
+ [[ ! -f /usr/share/nginx/hanabi-live/install/../.env ]]
+ cd /usr/share/nginx/hanabi-live/install/../client
+ npm install
npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but package-lock.json was generated for lockfileVersion@2. I'll try to do my best with it!

> @sentry/cli@1.66.0 install /usr/share/nginx/hanabi-live/client/node_modules/@sentry/cli
> node scripts/install.js

info sentry-cli Downloading from https://downloads.sentry-cdn.com/sentry-cli/1.66.0/sentry-cli-Linux-x86_64
Error: EACCES: permission denied, mkdir '/root/.npm/sentry-cli'
npm WARN eslint-config-airbnb@18.2.1 requires a peer of eslint-plugin-jsx-a11y@^6.4.1 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-config-airbnb@18.2.1 requires a peer of eslint-plugin-react@^7.21.5 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-config-airbnb@18.2.1 requires a peer of eslint-plugin-react-hooks@^4 || ^3 || ^2.3.0 || ^1.7.0 but none is installed. You must install peer dependencies yourself.
npm WARN linkifyjs@2.1.9 requires a peer of react@>= 0.14.0 but none is installed. You must install peer dependencies yourself.
npm WARN linkifyjs@2.1.9 requires a peer of react-dom@>= 0.14.0 but none is installed. You must install peer dependencies yourself.
npm WARN hanab-live-client@0.0.1 No description
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @sentry/cli@1.66.0 install: `node scripts/install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @sentry/cli@1.66.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-07-03T11_31_37_713Z-debug.log
```

The logs weren't really saying much more but for the sake of completeness here the interesting parts are:
```
423 warn eslint-config-airbnb@18.2.1 requires a peer of eslint-plugin-jsx-a11y@^6.4.1 but none is ins>
424 warn eslint-config-airbnb@18.2.1 requires a peer of eslint-plugin-react@^7.21.5 but none is insta>
425 warn eslint-config-airbnb@18.2.1 requires a peer of eslint-plugin-react-hooks@^4 || ^3 || ^2.3.0 >
426 warn linkifyjs@2.1.9 requires a peer of react@>= 0.14.0 but none is installed. You must install p>
427 warn linkifyjs@2.1.9 requires a peer of react-dom@>= 0.14.0 but none is installed. You must insta>
428 warn hanab-live-client@0.0.1 No description
429 warn optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules/fsevents):
430 warn notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":">
431 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
431 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
431 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   linux
431 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64
432 warn optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/chokidar/node_modules/f>
433 warn notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":>
434 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
434 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
434 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   linux
434 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64
435 verbose stack Error: @sentry/cli@1.66.0 install: `node scripts/install.js`
435 verbose stack Exit status 1
435 verbose stack     at EventEmitter.<anonymous> (/usr/share/npm/node_modules/npm-lifecycle/index.js>
435 verbose stack     at EventEmitter.emit (events.js:198:13)
435 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/node_modules/npm-lifecycle/lib/spaw>
435 verbose stack     at ChildProcess.emit (events.js:198:13)
435 verbose stack     at maybeClose (internal/child_process.js:982:16)
435 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
436 verbose pkgid @sentry/cli@1.66.0
437 verbose cwd /usr/share/nginx/hanabi-live/client
438 verbose Linux 5.4.0-77-generic
439 verbose argv "/usr/bin/node" "/usr/bin/npm" "install"
440 verbose node v10.19.0
441 verbose npm  v6.14.4
442 error code ELIFECYCLE
443 error errno 1
444 error @sentry/cli@1.66.0 install: `node scripts/install.js`
444 error Exit status 1
445 error Failed at the @sentry/cli@1.66.0 install script.
445 error This is probably not a problem with npm. There is likely additional logging output above.
446 verbose exit [ 1, true ]
```

Now I hope someone here is able to help me.

**Comment by Zamiell** [comment]
```
Error: EACCES: permission denied, mkdir '/root/.npm/sentry-cli'
```
you can see on this line it failed to install sentry
try installing deps as root

**Comment by nico1233** [comment]
Thanks for the help! I ran the command using root shell and additionally running the script with sudo.
